export const RECEIVE_DECKS = 'RECEIVE_DECKS';
export const RECEIVE_DECK = 'RECEIVE_DECK';
export const START_QUIZ = 'START_QUIZ';
export const INCREASE_SCORE = 'INCREASE_SCORE';
export const NEXT_QUESTION = 'NEXT_QUESTION';